# Generated by Django 6.0.5 on 2026-05-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_table',
            new_name='User',
        ),
    ]
